config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  
  get 'welcome/nannies'

  get 'welcome/help'

  get 'users/new'
  
  root  'welcome#home'
  
  match '/signup',  to: 'users#new',             via: 'get'
  
  get    'home'   => 'welcome#home'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  
  resources :users
  resources :nannies
  resources :account_activations, only: [:edit]
  

end

app/models/nanny.rb
class Nanny < ActiveRecord::Base
before_save { self.email = email.downcase }
validates :name, presence: true, length: { maximum: 50 }
VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
has_secure_password
validates :password, presence: true, length: { minimum: 6 }
  
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessor :remember_token, :activation_token
  before_save { self.email = email.downcase }
  before_create :create_activation_digest
  validates :name,  presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
                    
   has_secure_password
   
   # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
  # Returns true if the given token matches the digest.
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end
  
  # Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

   private

    # Converts email to all lower-case.
    def downcase_email
      self.email = email.downcase
    end

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end
  
end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/nannies_controller.rb
class NanniesController < ApplicationController
  
  def index
      @nannies = Nanny.paginate(page: params[:page], :per_page => 10)
  end
  
  
  def destroy
    Nanny.find(params[:id]).destroy
    flash[:success] = "This Nanny has been deleted"
    redirect_to nannies_url
  end
  
  
  def show
    @nanny = Nanny.find(params[:id])
  end
  
  def new
     @nanny = Nanny.new
  end
  
  def create
    @nanny = Nanny.new(nanny_params)
    if @nanny.save
      flash[:success] = "Welcome Nanny!"
     redirect_to @nanny
    else
      render 'new'
    end
  end
  
    def edit
    @nanny = Nanny.find(params[:id])
    end
  
   private

    def nanny_params
      params.require(:nanny).permit(:name, :email, :password,
                                   :password_confirmation)
    end
  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
       params[:session][:remember_me] == '1' ? remember(user) : forget(user)
      remember user
      redirect_to user
    else
      # Create an error message.
      flash.now[:danger] = 'Invalid email/password combination' 
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  before_action :admin_user,     only: :destroy

  def index
      @users = User.paginate(page: params[:page], :per_page => 10)
  end
  
  def show
  @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end
  
  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User deleted"
    redirect_to users_url
  end
  
  
  def create
    @user = User.new(user_params)    # Not the final implementation!
    if @user.save
      log_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
    
  end
  
  def edit
    @user = User.find(params[:id])
  end
  
  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "Congratulations, Profile updated"
      redirect_to @user
    else
      render 'edit'
    end
  end
  
  private

    def user_params
      params.require(:user).permit(:name, :email, :password,
                                   :password_confirmation)
    end
    
    # Confirms a logged-in user.
    def logged_in_user
      unless logged_in?
        flash[:danger] = "Please log in."
        redirect_to login_url
      end
    end
    
        # Confirms the correct user.
    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless @user == current_user
    end
    
     # Confirms an admin user.
    def admin_user
      redirect_to(root_url) unless current_user.admin?
    end

  
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def home
  end

  def nannies
  end

  def help
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/nannies_helper.rb
module NanniesHelper
  
  # Returns the Gravatar for the given user.
  def gravatar_for(nanny, options = { size: 250 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  # Logs in the given user.
  def log_in(user)
    session[:user_id] = user.id
  end
  
   # Remembers a user in a persistent session.
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end
  

  
    # Returns the user corresponding to the remember token cookie.
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in user
        @current_user = user
      end
    end
  end
  
   # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
   # Forgets a persistent session.
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

# Returns true if the given user is the current user.
  def current_user?(user)
    user == current_user
  end

  # Logs out the current user.
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
  
    # Returns the Gravatar for the given user.
  def gravatar_for(user, options = { size: 50 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    The <a href="#">Find me a Nanny</a>
    by <a href="#">Jack Kenna</a>
  </small>
  <nav>
    <ul>
      <li><%= link_to "About",   '#' %></li>
      <li><%= link_to "Contact", '#' %></li>
       <% if logged_in? %>
         <% if logged_in? && current_user.admin? %>
          <li><%= link_to "Users", users_path %></li>
          <% end %>
           <li><%= link_to "Account", current_user %></li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Find me a Nanny", home_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
          <li><%= link_to "Home",   home_path %></li>
          <li><%= link_to "Nannies", nannies_path %></li>
        <% if logged_in? %>
         <% if logged_in? && current_user.admin? %>
          <li><%= link_to "Users", users_path %></li>
          <% end %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
             <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: "delete" %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log in", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Find Me a Nanny</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
       <%= render 'layouts/footer' %>
        
    </div>
</body>
</html>

app/views/nannies/index.html.erb
<% provide(:title, 'All Nannies') %>
<h1>All Nannies</h1>
<% if logged_in? && current_user.admin? %>
<h2>You are an administrator, click the delete button to delete any nanny</h2>
<% end %>
<ul class="users">
  <%= will_paginate %>
  <% @nannies.each do |nanny| %>
    <li>
      <%= gravatar_for nanny, size: 50 %>
      <%= link_to nanny.name, nanny %>
         <% if logged_in? && current_user.admin? %>
    | <%= link_to "Delete", nanny, method: :delete,
                                  data: { confirm: "Are you sure?" } %>
  <% end %>
    </li>    
  <% end %>
</ul>
<%= will_paginate %>

app/views/nannies/new.html.erb
<% provide(:title, 'Nanny Sign up') %>
<h1>Nanny Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@nanny) do |f| %>
      <%= render 'shared/error_messages_nan' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/nannies/show.html.erb
<% provide(:title, @nanny.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @nanny %>
        <%= @nanny.name %>
      </h1>
    </section>
  </aside>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_error_messages_nan.html.erb
<% if @nanny.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@nanny.errors.count, "error") %>.
    </div>
    <ul>
    <% @nanny.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/users/edit.html.erb
<% provide(:title, "Edit user") %>
<h1>Update your profile</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Save changes", class: "btn btn-primary" %>
    <% end %>

    <div class="gravatar_edit">
      <%= gravatar_for @user %>
      <a href="http://gravatar.com/emails" target="_blank">change</a>
    </div>
  </div>
</div>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<% if logged_in? && current_user.admin? %>
<h2>You are an administrator, click the delete button to delete any nanny</h2>
<% end %>

<ul class="users">
  <%= will_paginate %>
  <% @users.each do |user| %>
    <li>
      <%= gravatar_for user, size: 50 %>
      <%= link_to user.name, user %>
         <% if current_user.admin? && !current_user?(user) %>
    | <%= link_to "Delete", user, method: :delete,
                                  data: { confirm: "Are you sure?" } %>
  <% end %>
    </li>
  <% end %>
</ul>
<%= will_paginate %>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= render 'shared/error_messages' %>

      <%= f.label :name %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email %>
      <%= f.email_field :email, class: 'form-control' %>

      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<%= @user.name %>, <%= @user.email %>
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= @user.name %>
        <%= gravatar_for @user %>
      </h1>
    </section>
        <br/>
        <%= link_to "Update Details", edit_user_path(current_user) , class: "btn btn-primary" %>
        <br/>
        <br/>
        <% if current_user.admin? %>
        <h3>You are an Administrator:</h3><br/><br/>
        <%= link_to "View/Delete Users", users_path , class: "btn btn-primary" %><br/><br/>
        <%= link_to "View/Delete Nannies", users_path , class: "btn btn-primary" %><br/><br/>
        <% end %>
        
        Name: <%= @user.name %><br/>
        Email: <%= @user.email %>
  </aside>
</div>

app/views/welcome/help.html.erb
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/#help">Rails Tutorial help section</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/welcome/home.html.erb
<div class="center jumbotron">
  <h1>Welcome to Find me a Nanny.com </h1>

  <h2>
    To facilitate you in finding your childcare professional
        <% if logged_in? %>
         <%= link_to "Your Account!", current_user %>
        <% else %>
         <%= link_to "Log in now!", login_path %>
        <% end %>
  </h2>
  
<% if logged_in? %>
  <%= link_to "Log out!",  logout_path, method: "delete", class: "btn btn-lg btn-primary" %>
<% else %>
  <%= link_to "Sign Up!", signup_path , class: "btn btn-lg btn-primary" %>
<% end %>
</div>
<div class="row">
 <div class="col-md-6 col-md-offset-3">
<div class="center jumbotron">
<h3>Find your nanny online now</h3><br/><br/>
    <form method="post" action="">
	 <label for="postcode">Enter your city, postcode or address</label>

        <input type="text" placeholder="LS6 2EG" name="postcode" class="form-control" required>	
<br/><br/>
	<%= link_to "Find Nanny!", signup_path , class: "btn btn-lg btn-primary" %>
<br/><br/>
		<label for="postcode">Distance Miles:</label>
		  <select name="miles">
            <option value="5">5</option>
            <option value="10">10</option>
            <option value="15">15</option>
             <option value="20">20</option>
              <option value="25">25</option>
               <option value="30">30</option>
        </select>
		</form>
		</div>
	</div>
</div>

app/views/welcome/nannies.html.erb
<h1>Welcome#nannies</h1>
<p>Find me in app/views/welcome/nannies.html.erb</p>